language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t burakunuvar/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true burakunuvar/client-test npm test

after_success:
  - docker build -t burakunuvar/multi-client ./client
  - docker build -t burakunuvar/multi-nginx./nginx
  - docker build -t burakunuvar/multi-api ./api
  - docker build -t burakunuvar/multi-worker ./worker
  # login and push all to docker-hub
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push burakunuvar/multi-client
  - docker push burakunuvar/multi-nginx
  - docker push burakunuvar/multi-api
  - docker push burakunuvar/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-158927923071"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
