language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t burakunuvar/client-test -f ./client/Dockerfile.dev .

script:
- docker run -e CI=true burakunuvar/client-test npm run test

after_success:
- docker build -t burakunuvar/client-prod ./client
- docker build -t burakunuvar/nginx-prod ./nginx
- docker build -t burakunuvar/server-prod ./server
- docker build -t burakunuvar/worker-prod ./worker
- echo "$docker_password" | docker login -u "$docker_username" --password-stdin
- docker push burakunuvar/client-prod ./client
- docker push burakunuvar/nginx-prod ./nginx
- docker push burakunuvar/server-prod ./server
- docker push burakunuvar/worker-prod ./worker
